language: go

install:
  - go get github.com/golang/dep/cmd/dep
  - go get github.com/golang/lint/golint

script:
  - dep ensure
  - gofmt -s -d . | xargs -r false
  - go build
  - go vet ./...
  - golint $(go list ./... | grep -v /vendor/) | xargs -r false
  - go test $(go list ./... | grep -v /vendor/)
