version: '3'

services:
  server:
    build: .
    restart: always
    ports:
      - '5656:5656'
    volumes:
      - "$HOME/.config/gol:/go/src/app/data"
    command: "--datapath /go/src/app/data/links.json server"
